<a href="https://colab.research.google.com/github/HEADHOTZ/PROGRAMMING-FUNDAMENTAL/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 67015080 ชื่อ : นายบุณยกร เกตุแก้ว

Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
days_in_month_leap_year = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
  if year % 400 == 0 and year % 100 == 0:
    return True
  elif year % 4 == 0 and year % 100 != 0:
    return True
  else:
    return False

def day_of_year(day, month, year):
  month_day = 0
  check_leap_year = leap_year(year)
  if check_leap_year == True:
    days = days_in_month_leap_year
  else:
    days = days_in_month

  for i in range(month-1):
    month_day += days[i]

  return day + month_day

# Testcases
print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 60

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 166
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 90
30 Jun 2023: 181
30 Sep 2023: 273
31 Dec 2023: 365


Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
days_in_month_leap_year = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def is_leap(year):
  if year % 400 == 0 and year % 100 == 0:
    return True
  elif year % 4 == 0 and year % 100 != 0:
    return True
  else:
    return False

def day_of_year(day, month, year):
  month_day = 0
  check_leap_year = leap_year(int(year))
  if check_leap_year == True:
    days = days_in_month_leap_year
  else:
    days = days_in_month

  for i in range(int(month)-1):
    month_day += days[i]

  return int(day) + month_day

def day_in_year(year):
    return 366 if is_leap(year) else 365

def date_diff(date1, date2):
    total_year = 0
    date1 = date1.split('-')
    date2 = date2.split('-')
    day_date1 = day_of_year(date1[0],date1[1],date1[2])
    day_date2 = day_of_year(date2[0],date2[1],date2[2])

    for i in range(int(date1[2]),int(date2[2])):
      total_year += day_in_year(i)

    day_date1 = day_of_year(int(date1[0]),int(date1[1]),int(date1[2]))
    day_date2 = day_of_year(int(date2[0]),int(date2[1]),int(date2[2]))

    return abs(total_year - abs(day_date1 - day_date2)) + 1

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 366 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)


731
76
367
366
366
365


Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
days_in_month_leap_year = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def is_leap(year):
  if year % 400 == 0 and year % 100 == 0:
    return True
  elif year % 4 == 0 and year % 100 != 0:
    return True
  else:
    return False

def day_of_year(day, month, year):
  month_day = 0
  check_leap_year = leap_year(int(year))
  if check_leap_year == True:
    days = days_in_month_leap_year
  else:
    days = days_in_month

  for i in range(int(month)-1):
    month_day += days[i]

  return int(day) + month_day

def day_in_year(year):
    return 366 if is_leap(year) else 365

def check_date(date1, date2):
  try:
    date1 = date1.split('-')
    date2 = date2.split('-')

    date1_day = int(date1[0])
    date1_month = int(date1[1])
    date1_year = int(date1[2])

    date2_day = int(date2[0])
    date2_month = int(date2[1])
    date2_year = int(date2[2])

    if leap_year(int(date1[2])) == True:
      days_date1 = days_in_month_leap_year
    else:
      days_date1 = days_in_month

    if leap_year(int(date2[2])) == True:
      days_date2 = days_in_month_leap_year
    else:
      days_date2 = days_in_month
  except:
    return -1

  if(date1_month < 1 or date1_month > 12) or (date2_month < 1 or date2_month > 12):
    return -1
  elif (date1_day > days_date1[date1_month-1]):
    return -1
  elif (date2_day > days_date2[date2_month-1]):
    return -1

def date_diff(date1, date2):
  if check_date(date1, date2) == -1:
    return -1

  else:
    total_year = 0
    date1 = date1.split('-')
    date2 = date2.split('-')
    day_date1 = day_of_year(date1[0],date1[1],date1[2])
    day_date2 = day_of_year(date2[0],date2[1],date2[2])

    for i in range(int(date1[2]),int(date2[2])):
      total_year += day_in_year(i)

    day_date1 = day_of_year(int(date1[0]),int(date1[1]),int(date1[2]))
    day_date2 = day_of_year(int(date2[0]),int(date2[1]),int(date2[2]))
    return abs(total_year - abs(day_date1 - day_date2)) + 1

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 366 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

# ทดสอบกรณีข้อมูลไม่ถูกต้อง
print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

731
76
367
366
366
365
-1
-1
-1
-1


1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()


In [24]:
import math

def simulate_fish_population(n, p, months=3):
  adult_male = n // 2
  adult_female = n // 2
  egg_cnt = 0
  baby_fish = 0
  month = 0

  for i in range(1, 121):
    month += 1
    if month % 2 == 0:
      egg_cnt += adult_female * 300

    if month % 3 == 0:
      baby_fish += egg_cnt * 0.9
      egg_count = 0

    adult_male += baby_fish * 0.5
    adult_female += baby_fish * 0.5
    baby_fish = 0

    adult_male *= (1 - p / 100)
    adult_female *= (1 - p / 100)

    if month % 3 == 0:
      total_adults = adult_male + adult_female
      print(f'เดือนที่ {month}', total_adults)

# Run simulation
n = 2  # Initial number of fish
p = 10  # Monthly mortality rate

simulate_fish_population(n, p)

# ถ้าเริ่มต้นด้วยปลา 2 ตัว ตายเดือนละ 10%
# เดือนที่ 1 ไข่ 300 ไบ
# เดือนที่ 2 ไข่ 300 ใบ + ลูกปลา 270 ตัว
# เดือนที่ 3 ไข่ 300 ใบ + ลูกปลา 270 ตัว + ปลาโตเต็มวัย 243 ตัว


เดือนที่ 3 220.15800000000002
เดือนที่ 6 48795.24175200001
เดือนที่ 9 5419966.163388409
เดือนที่ 12 1201267408.5868232
เดือนที่ 15 133431631323.08261
เดือนที่ 18 29573444769032.457
เดือนที่ 21 3284891399840122.0
เดือนที่ 24 7.280549103849275e+17
เดือนที่ 27 8.086921670481689e+19
เดือนที่ 30 1.7923645915292764e+22
เดือนที่ 33 1.990881710965827e+24
เดือนที่ 36 4.412539196074375e+26
เดือนที่ 39 4.901259278330726e+28
เดือนที่ 42 1.0863025440755961e+31
เดือนที่ 45 1.2066182727535927e+33
เดือนที่ 48 2.67431781300651e+35
เดือนที่ 51 2.9705175210374177e+37
เดือนที่ 54 6.583778896559607e+39
เดือนที่ 57 7.312979209782162e+41
เดือนที่ 60 1.6208299682248018e+44
เดือนที่ 63 1.8003484087859884e+46
เดือนที่ 66 3.990246068664932e+48
เดือนที่ 69 4.43219418521332e+50
เดือนที่ 72 9.823401590935807e+52
เดือนที่ 75 1.0911413146239483e+55
เดือนที่ 78 2.4183776427875062e+57
เดือนที่ 81 2.686230157630098e+59
เดือนที่ 84 5.953691670847494e+61
เดือนที่ 87 6.613105344882198e+63
เดือนที่ 90 1.4657117186487894e+66

2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน






In [9]:
def find_mismatch(str1, str2):
  str1 = str1.lower()
  str2 = str2.lower()

  if str1 == str2:
    return 0

  if abs(len(str1) - len(str2)) == 1:
    if len(str1) > len(str2):
      for i in range(len(str1)):
        if str1[:i] + str1[i+1:] == str2:
          return 1
    else:
      for i in range(len(str2)):
        if str2[:i] + str2[i+1:] == str1:
          return 1

  if len(str1) == len(str2):
    cnt_mismatch = 0
    for i in range(len(str1)):
      if str1[i] != str2[i]:
        cnt_mismatch += 1
      if cnt_mismatch > 1:
        return 2
    return 1
  return 2

print(find_mismatch('Python','Java'))
print(find_mismatch('book','boot'))
print(find_mismatch('fan','fun'))
print(find_mismatch('sin','sink'))
print(find_mismatch('Dog','dog'))
print(find_mismatch('poke','spoke'))
print(find_mismatch('poker','poke'))

2
1
1
1
0
1
1


3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|




In [10]:
def find_mismatch(str1, str2):
  str1 = str1.lower()
  str2 = str2.lower()

  if str1 == str2:
    return 0

  if abs(len(str1) - len(str2)) == 1:
    if len(str1) > len(str2):
      for i in range(len(str1)):
        if str1[:i] + str1[i+1:] == str2:
          return 1
    else:
      for i in range(len(str2)):
        if str2[:i] + str2[i+1:] == str1:
          return 1

  if len(str1) == len(str2):
    cnt_mismatch = 0
    for i in range(len(str1)):
      if str1[i] != str2[i]:
        cnt_mismatch += 1
      if cnt_mismatch > 1:
        return 2
    return 1
  return 2

def spelling_correction(input_string, correct_spells):
  words = input_string.split()
  corrected_sentence = []

  for word in words:
    if len(word) <= 2:
      corrected_sentence.append(word)
      continue

    corrected_word = word
    for correct_spell in correct_spells:
      mismatch_result = find_mismatch(word, correct_spell)
      if mismatch_result <= 1:
        corrected_word = correct_spell
        break

    corrected_sentence.append(corrected_word)

  return ' '.join(corrected_sentence)

print(spelling_correction('Thes is the Firs cas', ['that', 'first', 'case', 'car']))  # Output: 'thes is the first car'
print(spelling_correction('programming is fan and easy', ['programming', 'this', 'fun', 'easy', 'book']))  # Output: 'programming is fun and easy'
print(spelling_correction('Thes is vary essy', ['this', 'is', 'very', 'easy']))  # Output: 'this is very easy'
print(spelling_correction('Wee ipve Pythen', ['we', 'live', 'ln', 'Python']))  # Output: 'we live python'

Thes is the first case
programming is fun and easy
this is very easy
we ipve Python


4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]


In [20]:
def find_word_horizontal(crosswords, word):
    for row in range(len(crosswords)):
      for col in range(len(crosswords[0]) - len(word) + 1):
        if crosswords[row][col:col+len(word)] == list(word):
          return row, col
    return None

crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
word='cat'
find_word_horizontal(crosswords,word)

(0, 1)

5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]


In [4]:
def find_word_vertical(crosswords, word):
  word_arr = []
  for col in range(len(crosswords[0])):
    for row in range(len(crosswords) - len(word) + 1):
      if [crosswords[i][col] for i in range(row, row+len(word))] == list(word):
        word_arr.append(row)
        word_arr.append(col)
        return word_arr
  return None

crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
word='cat'
find_word_vertical(crosswords,word)

[1, 0]

6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```




In [8]:
def find_word_horizontal(crosswords, word):
    for row in range(len(crosswords)):
      for col in range(len(crosswords[0]) - len(word) + 1):
        if crosswords[row][col:col+len(word)] == list(word):
          return row, col
    return None

def find_word_vertical(crosswords, word):
  word_arr = []
  for col in range(len(crosswords[0])):
    for row in range(len(crosswords) - len(word) + 1):
      if [crosswords[i][col] for i in range(row, row+len(word))] == list(word):
        word_arr.append(row)
        word_arr.append(col)
        return word_arr
  return None

def capitalize_word_in_crossword(crosswords, word):
    table_test = [row[:] for row in crosswords]
    horizontal_position = find_word_horizontal(crosswords, word)
    if horizontal_position:
      row, col = horizontal_position
      for i in range(len(word)):
        table_test[row][col+i] = table_test[row][col+i].upper()

    vertical_position = find_word_vertical(crosswords, word)
    if vertical_position:
      row, col = vertical_position
      for i in range(len(word)):
        table_test[row+i][col] = table_test[row+i][col].upper()

    return table_test

crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)

[['s', 'd', 'o', 'g'],
 ['C', 'u', 'c', 'm'],
 ['A', 'C', 'A', 'T'],
 ['T', 'e', 't', 'k']]